import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { SidebarDemo } from "@/component/Sidemenu";
import Footer from "@/component/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} w-screen`} >

        <ClerkProvider >
          <SidebarDemo>
            {children}
            <Footer/>
          </SidebarDemo>
        </ClerkProvider>
      </body>
    </html>
  );
}
